#!/usr/bin/env ruby

require 'thor'
require 'fileutils'
require 'inifile'

module QtCreatorBackup
  class Base < Thor
    class_option :config, :default => File.join(ENV['HOME'], "/.config/QtProject/")
    class_option :backup, :default => "./qtcreator-config-backup/", :type => :string

    def initialize(*args)
      super
      @config = options[:config]
      @backup = options[:backup]

      snippets_path = "qtcreator/snippets"
      @config_snippets = File.join(@config, snippets_path)
      @backup_snippets = File.join(@backup, snippets_path)

      ini_name = "QtCreator.ini"
      @config_ini = File.join(@config, ini_name)
      @backup_ini = File.join(@backup, ini_name)
    end

  end

  class Backup < QtCreatorBackup::Base
    def initialize(*args)
      super
      prepare_backup
    end

    desc "snippets", "Copy snippets"
    def snippets
      FileUtils.cp_r @config_snippets, File.join(@backup_snippets, "..")
    end

    desc "settings", "Copy settings"
    option :sections, :type => :array,
      :default => [ "Analyzer", "Console", "CppCodeStyleSettings", "DebugMode", "DiffEditor", "EditorManager",
        "FakeVim", "FakeVimExCommand", "FakeVimUserCommand", "Git", "KeyboardShortcuts", "Mercurial", "Plugins", "QML",
        "QML.Inspector", "QbsProjectManager", "Subversion", "TodoPlugin", "Updater",
        "bazaar", "textDisplaySettings", "textMarginSettings" ]
    def settings
      config = IniFile.load(@config_ini)
      sections = options[:sections] & config.sections
      backup = IniFile.new
      sections.each do |section|
        backup[section] = config[section]
        backup.write(:filename => @backup_ini)
      end
    end

    desc "all", "Backup all"
    def all
      invoke :snippets
      invoke :settings
    end

    private
    def prepare_backup
      FileUtils.mkdir_p @backup
      FileUtils.mkdir_p @backup_snippets
    end
  end

  class Cli < Thor
    desc "backup", "backup [COMMAND [ARGS]]"
    subcommand "backup", Backup
  end
end

QtCreatorBackup::Cli.start(ARGV)
